<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DB::table('cities')->truncate();

        $cities = [
            ['id' => '1', 'city_name' => 'AHMEDABAD', 'country' => '99', 'city_status' => '1'],
            ['id' => '2', 'city_name' => 'ALLEPPEY', 'country' => '99', 'city_status' => '1'],
            ['id' => '3', 'city_name' => 'ANAND', 'country' => '99', 'city_status' => '1'],
            ['id' => '4', 'city_name' => 'AURANGABAD', 'country' => '99', 'city_status' => '1'],
            ['id' => '5', 'city_name' => 'BACHELI', 'country' => '99', 'city_status' => '1'],
            ['id' => '6', 'city_name' => 'BANGALORE', 'country' => '99', 'city_status' => '1'],
            ['id' => '7', 'city_name' => 'BANNERGHATTA', 'country' => '99', 'city_status' => '1'],
            ['id' => '8', 'city_name' => 'BELLARY', 'country' => '99', 'city_status' => '1'],
            ['id' => '9', 'city_name' => 'BHAVNAGAR', 'country' => '99', 'city_status' => '1'],
            ['id' => '10', 'city_name' => 'BHILAI', 'country' => '99', 'city_status' => '1'],
            ['id' => '11', 'city_name' => 'BHUBANESHWAR', 'country' => '99', 'city_status' => '1'],
            ['id' => '12', 'city_name' => 'BILASPUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '13', 'city_name' => 'CALICUT', 'country' => '99', 'city_status' => '1'],
            ['id' => '14', 'city_name' => 'CHANDIGARH', 'country' => '99', 'city_status' => '1'],
            ['id' => '15', 'city_name' => 'CHENNAI', 'country' => '99', 'city_status' => '1'],
            ['id' => '16', 'city_name' => 'CHITOOR', 'country' => '99', 'city_status' => '1'],
            ['id' => '17', 'city_name' => 'CITY', 'country' => '99', 'city_status' => '1'],
            ['id' => '18', 'city_name' => 'COCHIN', 'country' => '99', 'city_status' => '1'],
            ['id' => '19', 'city_name' => 'COIMBATORE', 'country' => '99', 'city_status' => '1'],
            ['id' => '20', 'city_name' => 'CUTTACK', 'country' => '99', 'city_status' => '1'],
            ['id' => '21', 'city_name' => 'DAVANGREE', 'country' => '99', 'city_status' => '1'],
            ['id' => '22', 'city_name' => 'DEHRADUN', 'country' => '99', 'city_status' => '1'],
            ['id' => '23', 'city_name' => 'DURGAPUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '24', 'city_name' => 'ERNAKULAM', 'country' => '99', 'city_status' => '1'],
            ['id' => '25', 'city_name' => 'ERODE', 'country' => '99', 'city_status' => '1'],
            ['id' => '26', 'city_name' => 'FARIDABAD', 'country' => '99', 'city_status' => '1'],
            ['id' => '27', 'city_name' => 'GHAZIABAD', 'country' => '99', 'city_status' => '1'],
            ['id' => '28', 'city_name' => 'GOA', 'country' => '99', 'city_status' => '1'],
            ['id' => '29', 'city_name' => 'GORAKHPUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '30', 'city_name' => 'GULBARGA', 'country' => '99', 'city_status' => '1'],
            ['id' => '31', 'city_name' => 'GURGAON', 'country' => '99', 'city_status' => '1'],
            ['id' => '32', 'city_name' => 'HARIDWAR', 'country' => '99', 'city_status' => '1'],
            ['id' => '33', 'city_name' => 'HUBLI', 'country' => '99', 'city_status' => '1'],
            ['id' => '34', 'city_name' => 'HYDERABAD', 'country' => '99', 'city_status' => '1'],
            ['id' => '35', 'city_name' => 'INDORE', 'country' => '99', 'city_status' => '1'],
            ['id' => '36', 'city_name' => 'JAIPUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '37', 'city_name' => 'JALANDHAR', 'country' => '99', 'city_status' => '1'],
            ['id' => '38', 'city_name' => 'JAMNAGAR', 'country' => '99', 'city_status' => '1'],
            ['id' => '39', 'city_name' => 'KAKINADA', 'country' => '99', 'city_status' => '1'],
            ['id' => '40', 'city_name' => 'KANCHEEPURAM', 'country' => '99', 'city_status' => '1'],
            ['id' => '41', 'city_name' => 'KANNUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '42', 'city_name' => 'KARAIKUDI', 'country' => '99', 'city_status' => '1'],
            ['id' => '43', 'city_name' => 'KARIMNAGAR', 'country' => '99', 'city_status' => '1'],
            ['id' => '44', 'city_name' => 'KARNATAKA', 'country' => '99', 'city_status' => '1'],
            ['id' => '45', 'city_name' => 'KARUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '46', 'city_name' => 'KOCHI', 'country' => '99', 'city_status' => '1'],
            ['id' => '47', 'city_name' => 'KOLHAPUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '48', 'city_name' => 'KOLKATA', 'country' => '99', 'city_status' => '1'],
            ['id' => '49', 'city_name' => 'KOLLAM', 'country' => '99', 'city_status' => '1'],
            ['id' => '50', 'city_name' => 'KOTTAYAM', 'country' => '99', 'city_status' => '1'],
            ['id' => '51', 'city_name' => 'KOVALAM', 'country' => '99', 'city_status' => '1'],
            ['id' => '52', 'city_name' => 'KOZHENCHERRY', 'country' => '99', 'city_status' => '1'],
            ['id' => '53', 'city_name' => 'KOZHIKODE', 'country' => '99', 'city_status' => '1'],
            ['id' => '54', 'city_name' => 'KRISHNAGIRI', 'country' => '99', 'city_status' => '1'],
            ['id' => '55', 'city_name' => 'LUCKNOW', 'country' => '99', 'city_status' => '1'],
            ['id' => '56', 'city_name' => 'LUDHIANA', 'country' => '99', 'city_status' => '1'],
            ['id' => '57', 'city_name' => 'MADURAI', 'country' => '99', 'city_status' => '1'],
            ['id' => '58', 'city_name' => 'MALAKPET', 'country' => '99', 'city_status' => '1'],
            ['id' => '59', 'city_name' => 'MALAPPURAM', 'country' => '99', 'city_status' => '1'],
            ['id' => '60', 'city_name' => 'MANGALORE', 'country' => '99', 'city_status' => '1'],
            ['id' => '61', 'city_name' => 'MARGAO', 'country' => '99', 'city_status' => '1'],
            ['id' => '62', 'city_name' => 'MEERUT', 'country' => '99', 'city_status' => '1'],
            ['id' => '63', 'city_name' => 'MOHALI', 'country' => '99', 'city_status' => '1'],
            ['id' => '64', 'city_name' => 'MUMBAI', 'country' => '99', 'city_status' => '1'],
            ['id' => '65', 'city_name' => 'MYSORE', 'country' => '99', 'city_status' => '1'],
            ['id' => '66', 'city_name' => 'NAGPUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '67', 'city_name' => 'NASHIK', 'country' => '99', 'city_status' => '1'],
            ['id' => '68', 'city_name' => 'NAVI MUMBAI', 'country' => '99', 'city_status' => '1'],
            ['id' => '69', 'city_name' => 'NEDUMBASSERY', 'country' => '99', 'city_status' => '1'],
            ['id' => '70', 'city_name' => 'NELLORE', 'country' => '99', 'city_status' => '1'],
            ['id' => '71', 'city_name' => 'NEW DELHI', 'country' => '99', 'city_status' => '1'],
            ['id' => '72', 'city_name' => 'NOIDA', 'country' => '99', 'city_status' => '1'],
            ['id' => '73', 'city_name' => 'ONGOLE', 'country' => '99', 'city_status' => '1'],
            ['id' => '74', 'city_name' => 'PALAKKAD', 'country' => '99', 'city_status' => '1'],
            ['id' => '75', 'city_name' => 'PALANI', 'country' => '99', 'city_status' => '1'],
            ['id' => '76', 'city_name' => 'PANAJI', 'country' => '99', 'city_status' => '1'],
            ['id' => '77', 'city_name' => 'PANCHKULA', 'country' => '99', 'city_status' => '1'],
            ['id' => '78', 'city_name' => 'PATHANAMTHITTA', 'country' => '99', 'city_status' => '1'],
            ['id' => '79', 'city_name' => 'PATIALA', 'country' => '99', 'city_status' => '1'],
            ['id' => '80', 'city_name' => 'PITAMPURA', 'country' => '99', 'city_status' => '1'],
            ['id' => '81', 'city_name' => 'PONDICHERRY', 'country' => '99', 'city_status' => '1'],
            ['id' => '82', 'city_name' => 'PORDENONE', 'country' => '99', 'city_status' => '1'],
            ['id' => '83', 'city_name' => 'PUDUKKOTAI', 'country' => '99', 'city_status' => '1'],
            ['id' => '84', 'city_name' => 'PUNE', 'country' => '99', 'city_status' => '1'],
            ['id' => '85', 'city_name' => 'RAIPUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '86', 'city_name' => 'RAJAHMUNDRY', 'country' => '99', 'city_status' => '1'],
            ['id' => '87', 'city_name' => 'RANCHI', 'country' => '99', 'city_status' => '1'],
            ['id' => '88', 'city_name' => 'RANIPET', 'country' => '99', 'city_status' => '1'],
            ['id' => '89', 'city_name' => 'REWARI', 'country' => '99', 'city_status' => '1'],
            ['id' => '90', 'city_name' => 'ROHINI', 'country' => '99', 'city_status' => '1'],
            ['id' => '91', 'city_name' => 'SALEM', 'country' => '99', 'city_status' => '1'],
            ['id' => '92', 'city_name' => 'SALT LAKE', 'country' => '99', 'city_status' => '1'],
            ['id' => '93', 'city_name' => 'SECUNDERABAD', 'country' => '99', 'city_status' => '1'],
            ['id' => '94', 'city_name' => 'SHIMOGA', 'country' => '99', 'city_status' => '1'],
            ['id' => '95', 'city_name' => 'SIVAKASI', 'country' => '99', 'city_status' => '1'],
            ['id' => '96', 'city_name' => 'SOMAJIGUDA', 'country' => '99', 'city_status' => '1'],
            ['id' => '97', 'city_name' => 'SURAT', 'country' => '99', 'city_status' => '1'],
            ['id' => '98', 'city_name' => 'THANE', 'country' => '99', 'city_status' => '1'],
            ['id' => '99', 'city_name' => 'THIRUVANANTHAPURAM', 'country' => '99', 'city_status' => '1'],
            ['id' => '100', 'city_name' => 'THRISSUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '101', 'city_name' => 'TIRUPATI', 'country' => '99', 'city_status' => '1'],
            ['id' => '102', 'city_name' => 'TIRUVANNAMALAI', 'country' => '99', 'city_status' => '1'],
            ['id' => '103', 'city_name' => 'TRICHY', 'country' => '99', 'city_status' => '1'],
            ['id' => '104', 'city_name' => 'TRIVANDRAM', 'country' => '99', 'city_status' => '1'],
            ['id' => '105', 'city_name' => 'TUMKUR', 'country' => '99', 'city_status' => '1'],
            ['id' => '106', 'city_name' => 'TUTICORIN', 'country' => '99', 'city_status' => '1'],
            ['id' => '107', 'city_name' => 'VADODRA', 'country' => '99', 'city_status' => '1'],
            ['id' => '108', 'city_name' => 'VARANASI', 'country' => '99', 'city_status' => '1'],
            ['id' => '109', 'city_name' => 'VELLORE', 'country' => '99', 'city_status' => '1'],
            ['id' => '110', 'city_name' => 'VIJAYAWADA', 'country' => '99', 'city_status' => '1'],
            ['id' => '111', 'city_name' => 'VISHAKHAPATNAM', 'country' => '99', 'city_status' => '1']
        ];

        DB::table('cities')->insert($cities);

    }
}
