<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DB::table('countries')->truncate();
        $countries = [
            ['code' => 'AF', 'name'=>'AFGHANISTAN', 'phonecode'=>93, 'country_status'=>1],
            ['code' => 'AL', 'name'=>'ALBANIA', 'phonecode'=>355, 'country_status'=>1],
            ['code' => 'DZ', 'name'=>'ALGERIA', 'phonecode'=>213, 'country_status'=>1],
            ['code' => 'AS', 'name'=>'AMERICAN SAMOA', 'phonecode'=>1684, 'country_status'=>1],
            ['code' => 'AD', 'name'=>'ANDORRA', 'phonecode'=>376, 'country_status'=>1],
            ['code' => 'AO', 'name'=>'ANGOLA', 'phonecode'=>244, 'country_status'=>1],
            ['code' => 'AI', 'name'=>'ANGUILLA', 'phonecode'=>1264, 'country_status'=>1],
            ['code' => 'AQ', 'name'=>'ANTARCTICA', 'phonecode'=>0, 'country_status'=>1],
            ['code' => 'AG', 'name'=>'ANTIGUA AND BARBUDA', 'phonecode'=>1268, 'country_status'=>1],
            ['code' => 'AR', 'name'=>'ARGENTINA', 'phonecode'=>54, 'country_status'=>1],
            ['code' => 'AM', 'name'=>'ARMENIA', 'phonecode'=>374, 'country_status'=>1],
            ['code' => 'AW', 'name'=>'ARUBA', 'phonecode'=>297, 'country_status'=>1],
            ['code' => 'AU', 'name'=>'AUSTRALIA', 'phonecode'=>61, 'country_status'=>1],
            ['code' => 'AT', 'name'=>'AUSTRIA', 'phonecode'=>43, 'country_status'=>1],
            ['code' => 'AZ', 'name'=>'AZERBAIJAN', 'phonecode'=>994, 'country_status'=>1],
            ['code' => 'BS', 'name'=>'BAHAMAS', 'phonecode'=>1242, 'country_status'=>1],
            ['code' => 'BH', 'name'=>'BAHRAIN', 'phonecode'=>973, 'country_status'=>1],
            ['code' => 'BD', 'name'=>'BANGLADESH', 'phonecode'=>880, 'country_status'=>1],
            ['code' => 'BB', 'name'=>'BARBADOS', 'phonecode'=>1246, 'country_status'=>1],
            ['code' => 'BY', 'name'=>'BELARUS', 'phonecode'=>375, 'country_status'=>1],
            ['code' => 'BE', 'name'=>'BELGIUM', 'phonecode'=>32, 'country_status'=>1],
            ['code' => 'BZ', 'name'=>'BELIZE', 'phonecode'=>501, 'country_status'=>1],
            ['code' => 'BJ', 'name'=>'BENIN', 'phonecode'=>229, 'country_status'=>1],
            ['code' => 'BM', 'name'=>'BERMUDA', 'phonecode'=>1441, 'country_status'=>1],
            ['code' => 'BT', 'name'=>'BHUTAN', 'phonecode'=>975, 'country_status'=>1],
            ['code' => 'BO', 'name'=>'BOLIVIA', 'phonecode'=>591, 'country_status'=>1],
            ['code' => 'BA', 'name'=>'BOSNIA AND HERZEGOVINA', 'phonecode'=>387, 'country_status'=>1],
            ['code' => 'BW', 'name'=>'BOTSWANA', 'phonecode'=>267, 'country_status'=>1],
            ['code' => 'BV', 'name'=>'BOUVET ISLAND', 'phonecode'=>0, 'country_status'=>1],
            ['code' => 'BR', 'name'=>'BRAZIL', 'phonecode'=>55, 'country_status'=>1],
            ['code' => 'IO', 'name'=>'BRITISH INDIAN OCEAN TERRITORY', 'phonecode'=>246, 'country_status'=>1],
            ['code' => 'BN', 'name'=>'BRUNEI DARUSSALAM', 'phonecode'=>673, 'country_status'=>1],
            ['code' => 'BG', 'name'=>'BULGARIA', 'phonecode'=>359, 'country_status'=>1],
            ['code' => 'BF', 'name'=>'BURKINA FASO', 'phonecode'=>226, 'country_status'=>1],
            ['code' => 'BI', 'name'=>'BURUNDI', 'phonecode'=>257, 'country_status'=>1],
            ['code' => 'KH', 'name'=>'CAMBODIA', 'phonecode'=>855, 'country_status'=>1],
            ['code' => 'CM', 'name'=>'CAMEROON', 'phonecode'=>237, 'country_status'=>1],
            ['code' => 'CA', 'name'=>'CANADA', 'phonecode'=>1, 'country_status'=>1],
            ['code' => 'CV', 'name'=>'CAPE VERDE', 'phonecode'=>238, 'country_status'=>1],
            ['code' => 'KY', 'name'=>'CAYMAN ISLANDS', 'phonecode'=>1345, 'country_status'=>1],
            ['code' => 'CF', 'name'=>'CENTRAL AFRICAN REPUBLIC', 'phonecode'=>236, 'country_status'=>1],
            ['code' => 'TD', 'name'=>'CHAD', 'phonecode'=>235, 'country_status'=>1],
            ['code' => 'CL', 'name'=>'CHILE', 'phonecode'=>56, 'country_status'=>1],
            ['code' => 'CN', 'name'=>'CHINA', 'phonecode'=>86, 'country_status'=>1],
            ['code' => 'CX', 'name'=>'CHRISTMAS ISLAND', 'phonecode'=>61, 'country_status'=>1],
            ['code' => 'CC', 'name'=>'COCOS (KEELING) ISLANDS', 'phonecode'=>672, 'country_status'=>1],
            ['code' => 'CO', 'name'=>'COLOMBIA', 'phonecode'=>57, 'country_status'=>1],
            ['code' => 'KM', 'name'=>'COMOROS', 'phonecode'=>269, 'country_status'=>1],
            ['code' => 'CG', 'name'=>'CONGO', 'phonecode'=>242, 'country_status'=>1],
            ['code' => 'CD', 'name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'phonecode'=>242, 'country_status'=>1],
            ['code' => 'CK', 'name'=>'COOK ISLANDS', 'phonecode'=>682, 'country_status'=>1],
            ['code' => 'CR', 'name'=>'COSTA RICA', 'phonecode'=>506, 'country_status'=>1],
            ['code' => 'CI', 'name'=>'COTE D\'IVOIRE', 'phonecode'=>225, 'country_status'=>1],
            ['code' => 'HR', 'name'=>'CROATIA', 'phonecode'=>385, 'country_status'=>1],
            ['code' => 'CU', 'name'=>'CUBA', 'phonecode'=>53, 'country_status'=>1],
            ['code' => 'CY', 'name'=>'CYPRUS', 'phonecode'=>357, 'country_status'=>1],
            ['code' => 'CZ', 'name'=>'CZECH REPUBLIC', 'phonecode'=>420, 'country_status'=>1],
            ['code' => 'DK', 'name'=>'DENMARK', 'phonecode'=>45, 'country_status'=>1],
            ['code' => 'DJ', 'name'=>'DJIBOUTI', 'phonecode'=>253, 'country_status'=>1],
            ['code' => 'DM', 'name'=>'DOMINICA', 'phonecode'=>1767, 'country_status'=>1],
            ['code' => 'DO', 'name'=>'DOMINICAN REPUBLIC', 'phonecode'=>1809, 'country_status'=>1],
            ['code' => 'EC', 'name'=>'ECUADOR', 'phonecode'=>593, 'country_status'=>1],
            ['code' => 'EG', 'name'=>'EGYPT', 'phonecode'=>20, 'country_status'=>1],
            ['code' => 'SV', 'name'=>'EL SALVADOR', 'phonecode'=>503, 'country_status'=>1],
            ['code' => 'GQ', 'name'=>'EQUATORIAL GUINEA', 'phonecode'=>240, 'country_status'=>1],
            ['code' => 'ER', 'name'=>'ERITREA', 'phonecode'=>291, 'country_status'=>1],
            ['code' => 'EE', 'name'=>'ESTONIA', 'phonecode'=>372, 'country_status'=>1],
            ['code' => 'ET', 'name'=>'ETHIOPIA', 'phonecode'=>251, 'country_status'=>1],
            ['code' => 'FK', 'name'=>'FALKLAND ISLANDS (MALVINAS)', 'phonecode'=>500, 'country_status'=>1],
            ['code' => 'FO', 'name'=>'FAROE ISLANDS', 'phonecode'=>298, 'country_status'=>1],
            ['code' => 'FJ', 'name'=>'FIJI', 'phonecode'=>679, 'country_status'=>1],
            ['code' => 'FI', 'name'=>'FINLAND', 'phonecode'=>358, 'country_status'=>1],
            ['code' => 'FR', 'name'=>'FRANCE', 'phonecode'=>33, 'country_status'=>1],
            ['code' => 'GF', 'name'=>'FRENCH GUIANA', 'phonecode'=>594, 'country_status'=>1],
            ['code' => 'PF', 'name'=>'FRENCH POLYNESIA', 'phonecode'=>689, 'country_status'=>1],
            ['code' => 'TF', 'name'=>'FRENCH SOUTHERN TERRITORIES', 'phonecode'=>0, 'country_status'=>1],
            ['code' => 'GA', 'name'=>'GABON', 'phonecode'=>241, 'country_status'=>1],
            ['code' => 'GM', 'name'=>'GAMBIA', 'phonecode'=>220, 'country_status'=>1],
            ['code' => 'GE', 'name'=>'GEORGIA', 'phonecode'=>995, 'country_status'=>1],
            ['code' => 'DE', 'name'=>'GERMANY', 'phonecode'=>49, 'country_status'=>1],
            ['code' => 'GH', 'name'=>'GHANA', 'phonecode'=>233, 'country_status'=>1],
            ['code' => 'GI', 'name'=>'GIBRALTAR', 'phonecode'=>350, 'country_status'=>1],
            ['code' => 'GR', 'name'=>'GREECE', 'phonecode'=>30, 'country_status'=>1],
            ['code' => 'GL', 'name'=>'GREENLAND', 'phonecode'=>299, 'country_status'=>1],
            ['code' => 'GD', 'name'=>'GRENADA', 'phonecode'=>1473, 'country_status'=>1],
            ['code' => 'GP', 'name'=>'GUADELOUPE', 'phonecode'=>590, 'country_status'=>1],
            ['code' => 'GU', 'name'=>'GUAM', 'phonecode'=>1671, 'country_status'=>1],
            ['code' => 'GT', 'name'=>'GUATEMALA', 'phonecode'=>502, 'country_status'=>1],
            ['code' => 'GN', 'name'=>'GUINEA', 'phonecode'=>224, 'country_status'=>1],
            ['code' => 'GW', 'name'=>'GUINEA-BISSAU', 'phonecode'=>245, 'country_status'=>1],
            ['code' => 'GY', 'name'=>'GUYANA', 'phonecode'=>592, 'country_status'=>1],
            ['code' => 'HT', 'name'=>'HAITI', 'phonecode'=>509, 'country_status'=>1],
            ['code' => 'HM', 'name'=>'HEARD ISLAND AND MCDONALD ISLANDS', 'phonecode'=>0, 'country_status'=>1],
            ['code' => 'VA', 'name'=>'HOLY SEE (VATICAN CITY STATE)', 'phonecode'=>39, 'country_status'=>1],
            ['code' => 'HN', 'name'=>'HONDURAS', 'phonecode'=>504, 'country_status'=>1],
            ['code' => 'HK', 'name'=>'HONG KONG', 'phonecode'=>852, 'country_status'=>1],
            ['code' => 'HU', 'name'=>'HUNGARY', 'phonecode'=>36, 'country_status'=>1],
            ['code' => 'IS', 'name'=>'ICELAND', 'phonecode'=>354, 'country_status'=>1],
            ['code' => 'IN', 'name'=>'INDIA', 'phonecode'=>91, 'country_status'=>1],
            ['code' => 'ID', 'name'=>'INDONESIA', 'phonecode'=>62, 'country_status'=>1],
            ['code' => 'IR', 'name'=>'IRAN, ISLAMIC REPUBLIC OF', 'phonecode'=>98, 'country_status'=>1],
            ['code' => 'IQ', 'name'=>'IRAQ', 'phonecode'=>964, 'country_status'=>1],
            ['code' => 'IE', 'name'=>'IRELAND', 'phonecode'=>353, 'country_status'=>1],
            ['code' => 'IL', 'name'=>'ISRAEL', 'phonecode'=>972, 'country_status'=>1],
            ['code' => 'IT', 'name'=>'ITALY', 'phonecode'=>39, 'country_status'=>1],
            ['code' => 'JM', 'name'=>'JAMAICA', 'phonecode'=>1876, 'country_status'=>1],
            ['code' => 'JP', 'name'=>'JAPAN', 'phonecode'=>81, 'country_status'=>1],
            ['code' => 'JO', 'name'=>'JORDAN', 'phonecode'=>962, 'country_status'=>1],
            ['code' => 'KZ', 'name'=>'KAZAKHSTAN', 'phonecode'=>7, 'country_status'=>1],
            ['code' => 'KE', 'name'=>'KENYA', 'phonecode'=>254, 'country_status'=>1],
            ['code' => 'KI', 'name'=>'KIRIBATI', 'phonecode'=>686, 'country_status'=>1],
            ['code' => 'KP', 'name'=>'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'phonecode'=>850, 'country_status'=>1],
            ['code' => 'KR', 'name'=>'KOREA, REPUBLIC OF', 'phonecode'=>82, 'country_status'=>1],
            ['code' => 'KW', 'name'=>'KUWAIT', 'phonecode'=>965, 'country_status'=>1],
            ['code' => 'KG', 'name'=>'KYRGYZSTAN', 'phonecode'=>996, 'country_status'=>1],
            ['code' => 'LA', 'name'=>'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'phonecode'=>856, 'country_status'=>1],
            ['code' => 'LV', 'name'=>'LATVIA', 'phonecode'=>371, 'country_status'=>1],
            ['code' => 'LB', 'name'=>'LEBANON', 'phonecode'=>961, 'country_status'=>1],
            ['code' => 'LS', 'name'=>'LESOTHO', 'phonecode'=>266, 'country_status'=>1],
            ['code' => 'LR', 'name'=>'LIBERIA', 'phonecode'=>231, 'country_status'=>1],
            ['code' => 'LY', 'name'=>'LIBYAN ARAB JAMAHIRIYA', 'phonecode'=>218, 'country_status'=>1],
            ['code' => 'LI', 'name'=>'LIECHTENSTEIN', 'phonecode'=>423, 'country_status'=>1],
            ['code' => 'LT', 'name'=>'LITHUANIA', 'phonecode'=>370, 'country_status'=>1],
            ['code' => 'LU', 'name'=>'LUXEMBOURG', 'phonecode'=>352, 'country_status'=>1],
            ['code' => 'MO', 'name'=>'MACAO', 'phonecode'=>853, 'country_status'=>1],
            ['code' => 'MK', 'name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'phonecode'=>389, 'country_status'=>1],
            ['code' => 'MG', 'name'=>'MADAGASCAR', 'phonecode'=>261, 'country_status'=>1],
            ['code' => 'MW', 'name'=>'MALAWI', 'phonecode'=>265, 'country_status'=>1],
            ['code' => 'MY', 'name'=>'MALAYSIA', 'phonecode'=>60, 'country_status'=>1],
            ['code' => 'MV', 'name'=>'MALDIVES', 'phonecode'=>960, 'country_status'=>1],
            ['code' => 'ML', 'name'=>'MALI', 'phonecode'=>223, 'country_status'=>1],
            ['code' => 'MT', 'name'=>'MALTA', 'phonecode'=>356, 'country_status'=>1],
            ['code' => 'MH', 'name'=>'MARSHALL ISLANDS', 'phonecode'=>692, 'country_status'=>1],
            ['code' => 'MQ', 'name'=>'MARTINIQUE', 'phonecode'=>596, 'country_status'=>1],
            ['code' => 'MR', 'name'=>'MAURITANIA', 'phonecode'=>222, 'country_status'=>1],
            ['code' => 'MU', 'name'=>'MAURITIUS', 'phonecode'=>230, 'country_status'=>1],
            ['code' => 'YT', 'name'=>'MAYOTTE', 'phonecode'=>269, 'country_status'=>1],
            ['code' => 'MX', 'name'=>'MEXICO', 'phonecode'=>52, 'country_status'=>1],
            ['code' => 'FM', 'name'=>'MICRONESIA, FEDERATED STATES OF', 'phonecode'=>691, 'country_status'=>1],
            ['code' => 'MD', 'name'=>'MOLDOVA, REPUBLIC OF', 'phonecode'=>373, 'country_status'=>1],
            ['code' => 'MC', 'name'=>'MONACO', 'phonecode'=>377, 'country_status'=>1],
            ['code' => 'MN', 'name'=>'MONGOLIA', 'phonecode'=>976, 'country_status'=>1],
            ['code' => 'MS', 'name'=>'MONTSERRAT', 'phonecode'=>1664, 'country_status'=>1],
            ['code' => 'MA', 'name'=>'MOROCCO', 'phonecode'=>212, 'country_status'=>1],
            ['code' => 'MZ', 'name'=>'MOZAMBIQUE', 'phonecode'=>258, 'country_status'=>1],
            ['code' => 'MM', 'name'=>'MYANMAR', 'phonecode'=>95, 'country_status'=>1],
            ['code' => 'NA', 'name'=>'NAMIBIA', 'phonecode'=>264, 'country_status'=>1],
            ['code' => 'NR', 'name'=>'NAURU', 'phonecode'=>674, 'country_status'=>1],
            ['code' => 'NP', 'name'=>'NEPAL', 'phonecode'=>977, 'country_status'=>1],
            ['code' => 'NL', 'name'=>'NETHERLANDS', 'phonecode'=>31, 'country_status'=>1],
            ['code' => 'AN', 'name'=>'NETHERLANDS ANTILLES', 'phonecode'=>599, 'country_status'=>1],
            ['code' => 'NC', 'name'=>'NEW CALEDONIA', 'phonecode'=>687, 'country_status'=>1],
            ['code' => 'NZ', 'name'=>'NEW ZEALAND', 'phonecode'=>64, 'country_status'=>1],
            ['code' => 'NI', 'name'=>'NICARAGUA', 'phonecode'=>505, 'country_status'=>1],
            ['code' => 'NE', 'name'=>'NIGER', 'phonecode'=>227, 'country_status'=>1],
            ['code' => 'NG', 'name'=>'NIGERIA', 'phonecode'=>234, 'country_status'=>1],
            ['code' => 'NU', 'name'=>'NIUE', 'phonecode'=>683, 'country_status'=>1],
            ['code' => 'NF', 'name'=>'NORFOLK ISLAND', 'phonecode'=>672, 'country_status'=>1],
            ['code' => 'MP', 'name'=>'NORTHERN MARIANA ISLANDS', 'phonecode'=>1670, 'country_status'=>1],
            ['code' => 'NO', 'name'=>'NORWAY', 'phonecode'=>47, 'country_status'=>1],
            ['code' => 'OM', 'name'=>'OMAN', 'phonecode'=>968, 'country_status'=>1],
            ['code' => 'PK', 'name'=>'PAKISTAN', 'phonecode'=>92, 'country_status'=>1],
            ['code' => 'PW', 'name'=>'PALAU', 'phonecode'=>680, 'country_status'=>1],
            ['code' => 'PS', 'name'=>'PALESTINIAN TERRITORY, OCCUPIED', 'phonecode'=>970, 'country_status'=>1],
            ['code' => 'PA', 'name'=>'PANAMA', 'phonecode'=>507, 'country_status'=>1],
            ['code' => 'PG', 'name'=>'PAPUA NEW GUINEA', 'phonecode'=>675, 'country_status'=>1],
            ['code' => 'PY', 'name'=>'PARAGUAY', 'phonecode'=>595, 'country_status'=>1],
            ['code' => 'PE', 'name'=>'PERU', 'phonecode'=>51, 'country_status'=>1],
            ['code' => 'PH', 'name'=>'PHILIPPINES', 'phonecode'=>63, 'country_status'=>1],
            ['code' => 'PN', 'name'=>'PITCAIRN', 'phonecode'=>0, 'country_status'=>1],
            ['code' => 'PL', 'name'=>'POLAND', 'phonecode'=>48, 'country_status'=>1],
            ['code' => 'PT', 'name'=>'PORTUGAL', 'phonecode'=>351, 'country_status'=>1],
            ['code' => 'PR', 'name'=>'PUERTO RICO', 'phonecode'=>1787, 'country_status'=>1],
            ['code' => 'QA', 'name'=>'QATAR', 'phonecode'=>974, 'country_status'=>1],
            ['code' => 'RE', 'name'=>'REUNION', 'phonecode'=>262, 'country_status'=>1],
            ['code' => 'RO', 'name'=>'ROMANIA', 'phonecode'=>40, 'country_status'=>1],
            ['code' => 'RU', 'name'=>'RUSSIAN FEDERATION', 'phonecode'=>70, 'country_status'=>1],
            ['code' => 'RW', 'name'=>'RWANDA', 'phonecode'=>250, 'country_status'=>1],
            ['code' => 'SH', 'name'=>'SAINT HELENA', 'phonecode'=>290, 'country_status'=>1],
            ['code' => 'KN', 'name'=>'SAINT KITTS AND NEVIS', 'phonecode'=>1869, 'country_status'=>1],
            ['code' => 'LC', 'name'=>'SAINT LUCIA', 'phonecode'=>1758, 'country_status'=>1],
            ['code' => 'PM', 'name'=>'SAINT PIERRE AND MIQUELON', 'phonecode'=>508, 'country_status'=>1],
            ['code' => 'VC', 'name'=>'SAINT VINCENT AND THE GRENADINES', 'phonecode'=>1784, 'country_status'=>1],
            ['code' => 'WS', 'name'=>'SAMOA', 'phonecode'=>684, 'country_status'=>1],
            ['code' => 'SM', 'name'=>'SAN MARINO', 'phonecode'=>378, 'country_status'=>1],
            ['code' => 'ST', 'name'=>'SAO TOME AND PRINCIPE', 'phonecode'=>239, 'country_status'=>1],
            ['code' => 'SA', 'name'=>'SAUDI ARABIA', 'phonecode'=>966, 'country_status'=>1],
            ['code' => 'SN', 'name'=>'SENEGAL', 'phonecode'=>221, 'country_status'=>1],
            ['code' => 'CS', 'name'=>'SERBIA AND MONTENEGRO', 'phonecode'=>381, 'country_status'=>1],
            ['code' => 'SC', 'name'=>'SEYCHELLES', 'phonecode'=>248, 'country_status'=>1],
            ['code' => 'SL', 'name'=>'SIERRA LEONE', 'phonecode'=>232, 'country_status'=>1],
            ['code' => 'SG', 'name'=>'SINGAPORE', 'phonecode'=>65, 'country_status'=>1],
            ['code' => 'SK', 'name'=>'SLOVAKIA', 'phonecode'=>421, 'country_status'=>1],
            ['code' => 'SI', 'name'=>'SLOVENIA', 'phonecode'=>386, 'country_status'=>1],
            ['code' => 'SB', 'name'=>'SOLOMON ISLANDS', 'phonecode'=>677, 'country_status'=>1],
            ['code' => 'SO', 'name'=>'SOMALIA', 'phonecode'=>252, 'country_status'=>1],
            ['code' => 'ZA', 'name'=>'SOUTH AFRICA', 'phonecode'=>27, 'country_status'=>1],
            ['code' => 'GS', 'name'=>'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'phonecode'=>0, 'country_status'=>1],
            ['code' => 'ES', 'name'=>'SPAIN', 'phonecode'=>34, 'country_status'=>1],
            ['code' => 'LK', 'name'=>'SRI LANKA', 'phonecode'=>94, 'country_status'=>1],
            ['code' => 'SD', 'name'=>'SUDAN', 'phonecode'=>249, 'country_status'=>1],
            ['code' => 'SR', 'name'=>'SURINAME', 'phonecode'=>597, 'country_status'=>1],
            ['code' => 'SJ', 'name'=>'SVALBARD AND JAN MAYEN', 'phonecode'=>47, 'country_status'=>1],
            ['code' => 'SZ', 'name'=>'SWAZILAND', 'phonecode'=>268, 'country_status'=>1],
            ['code' => 'SE', 'name'=>'SWEDEN', 'phonecode'=>46, 'country_status'=>1],
            ['code' => 'CH', 'name'=>'SWITZERLAND', 'phonecode'=>41, 'country_status'=>1],
            ['code' => 'SY', 'name'=>'SYRIAN ARAB REPUBLIC', 'phonecode'=>963, 'country_status'=>1],
            ['code' => 'TW', 'name'=>'TAIWAN, PROVINCE OF CHINA', 'phonecode'=>886, 'country_status'=>1],
            ['code' => 'TJ', 'name'=>'TAJIKISTAN', 'phonecode'=>992, 'country_status'=>1],
            ['code' => 'TZ', 'name'=>'TANZANIA, UNITED REPUBLIC OF', 'phonecode'=>255, 'country_status'=>1],
            ['code' => 'TH', 'name'=>'THAILAND', 'phonecode'=>66, 'country_status'=>1],
            ['code' => 'TL', 'name'=>'TIMOR-LESTE', 'phonecode'=>670, 'country_status'=>1],
            ['code' => 'TG', 'name'=>'TOGO', 'phonecode'=>228, 'country_status'=>1],
            ['code' => 'TK', 'name'=>'TOKELAU', 'phonecode'=>690, 'country_status'=>1],
            ['code' => 'TO', 'name'=>'TONGA', 'phonecode'=>676, 'country_status'=>1],
            ['code' => 'TT', 'name'=>'TRINIDAD AND TOBAGO', 'phonecode'=>1868, 'country_status'=>1],
            ['code' => 'TN', 'name'=>'TUNISIA', 'phonecode'=>216, 'country_status'=>1],
            ['code' => 'TR', 'name'=>'TURKEY', 'phonecode'=>90, 'country_status'=>1],
            ['code' => 'TM', 'name'=>'TURKMENISTAN', 'phonecode'=>7370, 'country_status'=>1],
            ['code' => 'TC', 'name'=>'TURKS AND CAICOS ISLANDS', 'phonecode'=>1649, 'country_status'=>1],
            ['code' => 'TV', 'name'=>'TUVALU', 'phonecode'=>688, 'country_status'=>1],
            ['code' => 'UG', 'name'=>'UGANDA', 'phonecode'=>256, 'country_status'=>1],
            ['code' => 'UA', 'name'=>'UKRAINE', 'phonecode'=>380, 'country_status'=>1],
            ['code' => 'AE', 'name'=>'UNITED ARAB EMIRATES', 'phonecode'=>971, 'country_status'=>1],
            ['code' => 'GB', 'name'=>'UNITED KINGDOM', 'phonecode'=>44, 'country_status'=>1],
            ['code' => 'US', 'name'=>'UNITED STATES', 'phonecode'=>1, 'country_status'=>1],
            ['code' => 'UM', 'name'=>'UNITED STATES MINOR OUTLYING ISLANDS', 'phonecode'=>1, 'country_status'=>1],
            ['code' => 'UY', 'name'=>'URUGUAY', 'phonecode'=>598, 'country_status'=>1],
            ['code' => 'UZ', 'name'=>'UZBEKISTAN', 'phonecode'=>998, 'country_status'=>1],
            ['code' => 'VU', 'name'=>'VANUATU', 'phonecode'=>678, 'country_status'=>1],
            ['code' => 'VE', 'name'=>'VENEZUELA', 'phonecode'=>58, 'country_status'=>1],
            ['code' => 'VN', 'name'=>'VIET NAM', 'phonecode'=>84, 'country_status'=>1],
            ['code' => 'VG', 'name'=>'VIRGIN ISLANDS, BRITISH', 'phonecode'=>1284, 'country_status'=>1],
            ['code' => 'VI', 'name'=>'VIRGIN ISLANDS, U.S.', 'phonecode'=>1340, 'country_status'=>1],
            ['code' => 'WF', 'name'=>'WALLIS AND FUTUNA', 'phonecode'=>681, 'country_status'=>1],
            ['code' => 'EH', 'name'=>'WESTERN SAHARA', 'phonecode'=>212, 'country_status'=>1],
            ['code' => 'YE', 'name'=>'YEMEN', 'phonecode'=>967, 'country_status'=>1],
            ['code' => 'ZM', 'name'=>'ZAMBIA', 'phonecode'=>260, 'country_status'=>1],
            ['code' => 'ZW', 'name'=>'ZIMBABWE', 'phonecode'=>263, 'country_status'=>1]
       ];
       DB::table('countries')->insert($countries);
    }
}
